from __future__ import annotations

DEVICES = [
    {
        "device_id": "LTAT-MUM-01",
        "gateway_id": "IGD-MUM-01",
        "facility_id": "FAC-MUM-HUB",
        "batch_id": "BATCH-CVX-002",
        "transport_mode": "storage",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "baseline_temperature": 5.1,
        "humidity_pct": 46.0,
        "battery_voltage": 2.72,
    },
    {
        "device_id": "LTAT-MUM-02",
        "gateway_id": "IGD-MUM-01",
        "facility_id": "FAC-MUM-HUB",
        "batch_id": "BATCH-OPV-001",
        "transport_mode": "storage",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "baseline_temperature": 4.8,
        "humidity_pct": 44.0,
        "battery_voltage": 3.10,
    },
    {
        "device_id": "LTAT-PUNE-TRUCK-01",
        "gateway_id": "IGD-PUNE-01",
        "facility_id": "FAC-PUNE-TRANSIT",
        "batch_id": "BATCH-CVX-001",
        "transport_mode": "transit",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "baseline_temperature": 4.8,
        "humidity_pct": 51.0,
        "battery_voltage": 2.58,
    },
    {
        "device_id": "LTAT-NASHIK-01",
        "gateway_id": "IGD-NASHIK-01",
        "facility_id": "FAC-NASHIK-CLINIC",
        "batch_id": "BATCH-CVX-001",
        "transport_mode": "field_storage",
        "latitude": 19.9975,
        "longitude": 73.7898,
        "baseline_temperature": 5.4,
        "humidity_pct": 48.0,
        "battery_voltage": 2.11,
    },
    {
        "device_id": "LTAT-AUR-01",
        "gateway_id": "IGD-AUR-01",
        "facility_id": "FAC-AUR-STORE",
        "batch_id": "BATCH-RVX-001",
        "transport_mode": "storage",
        "latitude": 19.8762,
        "longitude": 75.3433,
        "baseline_temperature": 5.2,
        "humidity_pct": 50.0,
        "battery_voltage": 2.95,
    },
    {
        "device_id": "LTAT-NGP-01",
        "gateway_id": "IGD-NGP-01",
        "facility_id": "FAC-NGP-HUB",
        "batch_id": "BATCH-IPV-001",
        "transport_mode": "storage",
        "latitude": 21.1458,
        "longitude": 79.0882,
        "baseline_temperature": 5.6,
        "humidity_pct": 45.0,
        "battery_voltage": 3.20,
    },
    {
        "device_id": "LTAT-KOL-01",
        "gateway_id": "IGD-KOL-01",
        "facility_id": "FAC-KOL-TRANSIT",
        "batch_id": "BATCH-OPV-001",
        "transport_mode": "transit",
        "latitude": 16.7050,
        "longitude": 74.2433,
        "baseline_temperature": 5.0,
        "humidity_pct": 49.0,
        "battery_voltage": 2.35,
    },
]
